### ISSUE TITLE
Start transaction in RestInterceptor

### ISSUE THREAD

**Issue by ilvalerione** [inspector-apm/inspector-spring#1]
https://github.com/inspector-apm/inspector-spring/blob/34087d3fae4a2a3c58b5893a2cf318be4a103f93/src/main/java/dev/inspector/spring/interceptors/rest/RestInterceptor.java#L27-L37

`pattern` non credo proprio possa essere null. Per cui questo blocco di codice diventa:

```java
if (configProperties.getPathList().contains(pattern)) {
    inspector.startTransaction(String.format("%s %s", request.getMethod(), pattern));
}
```

**Comment by elitesoftwarehouse** [comment]
già  fixato
